name: Push master to main prod 

on: 
  push:
    branches: 
      - master
jobs:
  master-build:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest

    steps:
    - name: Connect via ssh to put down docker-compose server 
      uses: appleboy/ssh-action@master        
      with:
        host: 164.68.126.191
        username: root
        port: 22
        password: Berane983
        script: |
          cd /srv/www/roofy/prod/
          docker-compose -f  prod-docker-compose.yml down --volumes
          rm -r -f /srv/www/roofy/prod/
          mkdir -p /srv/www/roofy/prod/
    - name: Reconnect via ssh to add docker-compose/dockerfile and run server 
      uses: appleboy/ssh-action@master        
      with:
        host: 164.68.126.191
        username: root
        port: 22
        password: Berane983
        script: |
          git clone -b master https://02a8cd789e7ac05dc4852b7272b9869cf489ddb7:x-oauth-basic@github.com/cpcaballero/roofy-angular.git /srv/www/roofy/prod
          cd /srv/www/roofy/docker-files
          cp prod-docker-compose.yml /srv/www/roofy/prod
          cp default.conf /srv/www/roofy/prod
          cp stage-roofy-frontend-dockerfile.dev /srv/www/roofy/stage
          cd ../prod
          docker-compose -f  prod-docker-compose.yml up -d --build --force-recreate
          docker ps -a 
